-- Grant necessary permissions to insync_user
GRANT ALL PRIVILEGES ON DATABASE insync_db TO insync_user;
GRANT ALL PRIVILEGES ON SCHEMA public TO insync_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO insync_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO insync_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO insync_user;

-- Grant future permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO insync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO insync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO insync_user; 